In [2]:
import numpy as np

In [4]:
b = np.zeros((5,2), dtype="f8")
b

array([[ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.]])

In [5]:
b.dtype

dtype('float64')

In [8]:
c = np.zeros(5, dtype="S4")
c

array([b'', b'', b'', b'', b''], 
      dtype='|S4')

In [10]:
c[0] = "abcd"
c[1] = "ABCDE"
c

array([b'abcd', b'ABCD', b'', b'', b''], 
      dtype='|S4')

In [12]:

d = np.ones((2,3,4), dtype="i8")
d

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int64)

In [14]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [16]:
a.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [18]:
a.reshape(2,-1,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [20]:
a.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [22]:
b = a.reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [25]:
z = b[:,np.newaxis]

In [27]:
z.shape

(3, 1, 4)

In [28]:
import matplotlib as plt

In [30]:
x = np.linspace(-0.9, 2.9, 100)
y = x**3 - 3*x**2 + x
plt.plot(x, y);

AttributeError: module 'matplotlib' has no attribute 'plot'

In [31]:
x = np.arange(1, 101)
x

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [32]:
y = np.arange(101,201)
y

array([101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113,
       114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126,
       127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139,
       140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152,
       153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165,
       166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178,
       179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191,
       192, 193, 194, 195, 196, 197, 198, 199, 200])

In [33]:
x + y

array([102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126,
       128, 130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152,
       154, 156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178,
       180, 182, 184, 186, 188, 190, 192, 194, 196, 198, 200, 202, 204,
       206, 208, 210, 212, 214, 216, 218, 220, 222, 224, 226, 228, 230,
       232, 234, 236, 238, 240, 242, 244, 246, 248, 250, 252, 254, 256,
       258, 260, 262, 264, 266, 268, 270, 272, 274, 276, 278, 280, 282,
       284, 286, 288, 290, 292, 294, 296, 298, 300])

In [35]:
print(zip(x,y))

In [37]:
z = np.zeros_like(x)
for i, (xi, yi) in enumerate(zip(x, y)):
    z[i] = xi + yi

In [38]:
z

array([102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126,
       128, 130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152,
       154, 156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178,
       180, 182, 184, 186, 188, 190, 192, 194, 196, 198, 200, 202, 204,
       206, 208, 210, 212, 214, 216, 218, 220, 222, 224, 226, 228, 230,
       232, 234, 236, 238, 240, 242, 244, 246, 248, 250, 252, 254, 256,
       258, 260, 262, 264, 266, 268, 270, 272, 274, 276, 278, 280, 282,
       284, 286, 288, 290, 292, 294, 296, 298, 300])