# Numpy

- <b>수치해석용</b> Python 라이브러리
- C로 구현 (파이썬용 C라이브러리)
- BLAS/LAPACK 기반
- 빠른 수치 계산을 위한 Structured Array 제공

In [1]:
import numpy as np
list = [0,1,2,3,4]
a = np.array(list)
a

array([0, 1, 2, 3, 4])

In [6]:
L = range(1000)
%timeit [i**2 for i in L]

1000 loops, best of 3: 287 µs per loop


In [7]:
a = np.arange(1000)
%timeit a**2

The slowest run took 15.97 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 1.47 µs per loop


In [11]:
a = np.array([0, 1, 2, 3])
a
a.ndim
a

array([0, 1, 2, 3])

In [13]:
a = np.arange(10)
a 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])