# NumPy Basics: Arrays and Vectorized Computation

In [1]:
%matplotlib inline
from __future__ import division
from numpy.random import randn
import numpy as np
np.set_printoptions(precision=4, suppress=True)

## The NumPy ndarray: a multidimensional array object

In [2]:
data = randn(2,3)

In [4]:
data

array([[-0.0785, -1.883 , -0.1127],
       [-0.1043, -1.8937, -0.0617]])

In [5]:
data+data

array([[-0.1571, -3.7661, -0.2253],
       [-0.2087, -3.7874, -0.1233]])

In [6]:
data + 2

array([[ 1.9215,  0.117 ,  1.8873],
       [ 1.8957,  0.1063,  1.9383]])

In [7]:
data * 2 

array([[-0.1571, -3.7661, -0.2253],
       [-0.2087, -3.7874, -0.1233]])

In [8]:
data.shape

(2, 3)

In [9]:
data.dtype

dtype('float64')

### Creating ndarrays

In [10]:
data1 = [6,7.5,8,0,1]
arr1 = np.array(data1)
arr1

array([ 6. ,  7.5,  8. ,  0. ,  1. ])

In [12]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [13]:
print(arr2.ndim)
print(arr2.shape)

2
(2, 4)


In [14]:
arr1.dtype

dtype('float64')

In [15]:
arr2.dtype

dtype('int32')

In [16]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [17]:
np.zeros((3,6))

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

In [18]:
np.empty((2,3,2))

array([[[  1.2838e-311,   6.3660e-314],
        [  0.0000e+000,   1.2732e-313],
        [  1.2732e-313,   1.2732e-313]],

       [[  1.1101e-047,   1.9547e-313],
        [  2.6964e+184,   2.7586e-313],
        [  6.7580e+170,   9.9531e-043]]])

In [19]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

### Data Types for ndarrays

In [20]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)

In [21]:
arr1.dtype

dtype('float64')

In [22]:
arr2.dtype

dtype('int32')

In [23]:
int_array = np.arange(10)
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)
int_array.astype(calibers.dtype)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

In [24]:
empty_uint32 = np.empty(8, dtype='u4')
empty_uint32

array([0, 0, 0, 0, 0, 0, 0, 0], dtype=uint32)

### Operations between arrays and scalars

In [25]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

In [26]:
arr + arr

array([[  2.,   4.,   6.],
       [  8.,  10.,  12.]])

In [27]:
arr - arr

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [28]:
1 / arr

array([[ 1.    ,  0.5   ,  0.3333],
       [ 0.25  ,  0.2   ,  0.1667]])

In [29]:
arr ** 0.5

array([[ 1.    ,  1.4142,  1.7321],
       [ 2.    ,  2.2361,  2.4495]])

### Basic indexing and slicing

In [30]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
arr[5]

5

In [32]:
arr[5:8]

array([5, 6, 7])

In [33]:
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [34]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

In [35]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [36]:
arr_slice[1] = 12345
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,     9])

In [37]:
arr_slice[:] = 64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [38]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [39]:
arr2d[2]

array([7, 8, 9])

In [40]:
arr2d[0][2]

3

In [41]:
arr2d[0, 2]

3

In [42]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [43]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [44]:
old_values = arr3d[0].copy()
old_values

array([[1, 2, 3],
       [4, 5, 6]])

In [45]:
arr3d[0] = 42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [46]:
arr3d[0] = old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [47]:
arr3d[1, 0]

array([7, 8, 9])

### Boolean indexing

In [48]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = randn(7, 4)

In [49]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], 
      dtype='<U4')

In [50]:
data

array([[-0.8523,  0.556 ,  1.8235, -0.9577],
       [ 0.0423,  0.6854, -0.0848,  0.9806],
       [ 0.0523, -0.2726, -0.5086,  0.8704],
       [-0.7045, -0.059 , -0.1501, -0.3412],
       [-1.5655, -0.776 , -0.3873, -0.6678],
       [-0.0664, -0.1149, -0.6447, -0.6978],
       [-1.3493,  0.3423,  0.0015,  0.5489]])

In [51]:
names == 'Bob'

array([ True, False, False,  True, False, False, False], dtype=bool)

In [52]:
data[names == 'Bob']

array([[-0.8523,  0.556 ,  1.8235, -0.9577],
       [-0.7045, -0.059 , -0.1501, -0.3412]])

In [53]:
data[names == 'Bob', 2:]

array([[ 1.8235, -0.9577],
       [-0.1501, -0.3412]])

In [54]:
data[names == 'Bob', 3]

array([-0.9577, -0.3412])

In [55]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True], dtype=bool)

In [56]:
data[-(names == 'Bob')]

C:\Anaconda3\envs\work\lib\site-packages\ipykernel\__main__.py:1: DeprecationWarning: numpy boolean negative, the `-` operator, is deprecated, use the `~` operator or the logical_not function instead.
  if __name__ == '__main__':


array([[ 0.0423,  0.6854, -0.0848,  0.9806],
       [ 0.0523, -0.2726, -0.5086,  0.8704],
       [-1.5655, -0.776 , -0.3873, -0.6678],
       [-0.0664, -0.1149, -0.6447, -0.6978],
       [-1.3493,  0.3423,  0.0015,  0.5489]])

In [57]:
mask = (names == 'Bob') | (names == 'Will')
mask

array([ True, False,  True,  True,  True, False, False], dtype=bool)

In [59]:
data[mask]

array([[-0.8523,  0.556 ,  1.8235, -0.9577],
       [ 0.0523, -0.2726, -0.5086,  0.8704],
       [-0.7045, -0.059 , -0.1501, -0.3412],
       [-1.5655, -0.776 , -0.3873, -0.6678]])

In [60]:
data[data < 0] = 0
data

array([[ 0.    ,  0.556 ,  1.8235,  0.    ],
       [ 0.0423,  0.6854,  0.    ,  0.9806],
       [ 0.0523,  0.    ,  0.    ,  0.8704],
       [ 0.    ,  0.    ,  0.    ,  0.    ],
       [ 0.    ,  0.    ,  0.    ,  0.    ],
       [ 0.    ,  0.    ,  0.    ,  0.    ],
       [ 0.    ,  0.3423,  0.0015,  0.5489]])

In [61]:
data[names != 'Joe'] = 7
data

array([[ 7.    ,  7.    ,  7.    ,  7.    ],
       [ 0.0423,  0.6854,  0.    ,  0.9806],
       [ 7.    ,  7.    ,  7.    ,  7.    ],
       [ 7.    ,  7.    ,  7.    ,  7.    ],
       [ 7.    ,  7.    ,  7.    ,  7.    ],
       [ 0.    ,  0.    ,  0.    ,  0.    ],
       [ 0.    ,  0.3423,  0.0015,  0.5489]])

### Transposing arrays and swapping axes

In [62]:
arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [63]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [64]:
arr = np.random.randn(6, 3)
arr

array([[-1.7852, -0.2039,  0.2643],
       [ 0.0433, -0.431 , -0.3394],
       [ 0.1012, -0.4697, -0.7151],
       [-0.6173,  0.3538, -0.1594],
       [-0.3114, -0.4668, -0.6747],
       [-1.3016, -0.3475, -0.5348]])

In [65]:
np.dot(arr.T, arr)

array([[ 5.3713,  0.6771,  0.4458],
       [ 0.6771,  0.9117,  0.8726],
       [ 0.4458,  0.8726,  1.4631]])

In [66]:
arr = np.arange(16).reshape((2, 2, 4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [67]:
arr.transpose((1, 0, 2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [68]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [69]:
arr.swapaxes(1, 2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

## Universal Functions: Fast element-wise array functions

In [70]:
arr = np.arange(10)
np.sqrt(arr)

array([ 0.    ,  1.    ,  1.4142,  1.7321,  2.    ,  2.2361,  2.4495,
        2.6458,  2.8284,  3.    ])

In [71]:
np.exp(arr)

array([    1.    ,     2.7183,     7.3891,    20.0855,    54.5982,
         148.4132,   403.4288,  1096.6332,  2980.958 ,  8103.0839])

In [73]:
x = randn(8)
y = randn(8)
x

array([-1.0898,  0.3308, -0.152 ,  0.6657, -1.6503, -0.3807, -0.0487,
       -1.3587])

In [74]:
y

array([-1.7752,  0.1422,  0.733 , -0.4088, -0.5906,  0.6244, -0.5128,
       -0.9168])

In [75]:
np.maximum(x, y) # element-wise maximum

array([-1.0898,  0.3308,  0.733 ,  0.6657, -0.5906,  0.6244, -0.0487,
       -0.9168])

In [76]:
arr = randn(7) * 5
arr

array([-0.983 , -0.249 , -4.5595,  4.7611, -1.6459, -1.7326, -0.3711])

In [77]:
np.modf(arr)

(array([-0.983 , -0.249 , -0.5595,  0.7611, -0.6459, -0.7326, -0.3711]),
 array([-0., -0., -4.,  4., -1., -1., -0.]))