# Db_Guide 
 - 동영상 강의  

In [4]:
import numpy as np
a2 = np.random.randn(100,100) # 100 x 100 random 난수 생성. 
a2

array([[ 0.53166387,  0.20461799,  0.17084032, ..., -0.44995304,
         1.26740653,  1.93792018],
       [ 0.58040329,  1.77139721, -0.13823706, ..., -0.75976417,
         1.50469084,  0.21141867],
       [ 0.92099846,  1.04122953, -1.46378516, ...,  0.07190852,
         0.94998019, -0.9072831 ],
       ..., 
       [-0.2632543 ,  0.96464074, -0.2773548 , ...,  2.44557298,
        -1.14682209,  0.54532833],
       [ 0.64257772,  0.56928947, -1.48306429, ...,  1.65020873,
        -1.09800943, -0.29625878],
       [ 1.72501019, -0.47456146, -0.33650947, ...,  0.85472158,
        -1.08369257,  0.67886572]])

In [9]:
%timeit np.dot(a2,a2)  # a2 * a2   # 수행되는 시간 확인. 

The slowest run took 35.31 times longer than the fastest. This could mean that an intermediate result is being cached.
10000 loops, best of 3: 28.5 µs per loop


In [11]:
foo = "automatic"
foo

'automatic'

In [13]:
!dir  # ! 시스템 커맨드 

 F 드라이브의 볼륨에는 이름이 없습니다.
 볼륨 일련 번호: 6646-05F5

 F:\#BigdataMBA\#2. PYTHON\iPython(방학) 디렉터리

2016-07-11  오후 11:15    <DIR>          .
2016-07-11  오후 11:15    <DIR>          ..
2016-07-05  오후 10:55            39,515 1.png
2016-07-05  오후 10:55            28,245 2.png
2016-07-06  오후 11:27            44,930 3.PNG
2016-07-08  오전 12:34             5,448 4.PNG
2016-07-08  오전 12:34             3,303 5.PNG
2016-07-10  오후 03:51             5,647 6.PNG
2016-07-11  오후 09:17            13,127 7.PNG
2016-07-10  오후 03:00           121,090 Chapter 1. 파이썬 기초 1 ( 기본, 자료형 ).ipynb
2016-07-08  오전 12:34            78,699 Chapter 2. 파이썬 기초 2 (변수, 제어문).ipynb
2016-07-10  오후 02:34            32,298 Chapter 3. 파이썬 기초 (함수, 입출력).ipynb
2016-07-11  오후 09:04            11,736 Chapter 4. 파이썬 기초 ( 클래스 ).ipynb
2016-07-11  오후 10:10           290,646 Chapter 5. 모듈 .ipynb
2016-07-11  오후 10:54           189,299 Chapter 6. 데이터 분석 예제 [ 타이타닉 ].ipynb
2016-07-11  오후 11:15             2,236 Chapter 7. 데이터 분석 [ DB_Guide Video ].ipyn

In [15]:
from numpy.random import randn
import numpy as np

In [19]:
data = randn(2,3)
data

array([[ 0.96805776,  1.60181275,  1.44934333],
       [-1.03226097, -0.7376646 , -1.66541407]])

In [21]:
data * 10

array([[  9.68057765,  16.01812752,  14.49343327],
       [-10.32260968,  -7.37664601, -16.65414067]])

In [23]:
data + data

array([[ 1.93611553,  3.2036255 ,  2.89868665],
       [-2.06452194, -1.4753292 , -3.33082813]])

In [26]:
data.shape  # row, col 

(2, 3)

In [29]:
data.dtype

dtype('float64')

In [31]:
data1 = [3.4,23.2,5.5,1,0]

In [33]:
data2 = [[1,2,3,4],[5,6,7,8]]