# Final Test (Classification)

## 데이터 불러오기

In [1]:
import pandas as pd

In [2]:
train = pd.read_csv('train.csv')

In [3]:
train.head()

age         workclass  education             marital         occupation  \
0   39         State-gov         13       Never-married       Adm-clerical   
1   50  Self-emp-not-inc         13  Married-civ-spouse    Exec-managerial   
2   38           Private          9            Divorced  Handlers-cleaners   
3   53           Private          7  Married-civ-spouse  Handlers-cleaners   
4   28           Private         13  Married-civ-spouse     Prof-specialty   

    relationship   race     sex  capital_gain  capital_loss  hours_per_week  \
0  Not-in-family  White    Male          2174             0              40   
1        Husband  White    Male             0             0              13   
2  Not-in-family  White    Male             0             0              40   
3        Husband  Black    Male             0             0              40   
4           Wife  Black  Female             0             0              40   

     income  
0  under50k  
1  under50k  
2  under50k  
3  under50k  
4  under50k

In [4]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24999 entries, 0 to 24998
Data columns (total 12 columns):
age               24999 non-null int64
workclass         24999 non-null object
education         24999 non-null int64
marital           24999 non-null object
occupation        24999 non-null object
relationship      24999 non-null object
race              24999 non-null object
sex               24999 non-null object
capital_gain      24999 non-null int64
capital_loss      24999 non-null int64
hours_per_week    24999 non-null int64
income            24999 non-null object
dtypes: int64(5), object(7)
memory usage: 2.3+ MB


## 독립변수

In [5]:
train.columns

Index(['age', 'workclass', 'education', 'marital', 'occupation',
       'relationship', 'race', 'sex', 'capital_gain', 'capital_loss',
       'hours_per_week', 'income'],
      dtype='object')

In [6]:
indep = train.columns[:-1]

In [7]:
discrete = []
continuous = []
for v in indep:
    if train[v].dtype == 'object':
        discrete.append(v)
    else:
        continuous.append(v)

In [8]:
discrete

['workclass', 'marital', 'occupation', 'relationship', 'race', 'sex']

In [9]:
continuous

['age', 'education', 'capital_gain', 'capital_loss', 'hours_per_week']

In [10]:
dummy = pd.get_dummies(train[discrete])
X = pd.concat([train[continuous], dummy], axis=1)

In [11]:
X.head()

age  education  capital_gain  capital_loss  hours_per_week  \
0   39         13          2174             0              40   
1   50         13             0             0              13   
2   38          9             0             0              40   
3   53          7             0             0              40   
4   28         13             0             0              40   

   workclass_Federal-gov  workclass_Local-gov  workclass_Private  \
0                    0.0                  0.0                0.0   
1                    0.0                  0.0                0.0   
2                    0.0                  0.0                1.0   
3                    0.0                  0.0                1.0   
4                    0.0                  0.0                1.0   

   workclass_Self-emp-inc  workclass_Self-emp-not-inc    ...     \
0                     0.0                         0.0    ...      
1                     0.0                         1.0    ...      
2                     0.0                         0.0    ...      
3                     0.0                         0.0    ...      
4                     0.0                         0.0    ...      

   relationship_Own-child  relationship_Unmarried  relationship_Wife  \
0                     0.0                     0.0                0.0   
1                     0.0                     0.0                0.0   
2                     0.0                     0.0                0.0   
3                     0.0                     0.0                0.0   
4                     0.0                     0.0                1.0   

   race_Amer-Indian-Eskimo  race_Asian-Pac-Islander  race_Black  race_Other  \
0                      0.0                      0.0         0.0         0.0   
1                      0.0                      0.0         0.0         0.0   
2                      0.0                      0.0         0.0         0.0   
3                      0.0                      0.0         1.0         0.0   
4                      0.0                      0.0         1.0         0.0   

   race_White  sex_Female  sex_Male  
0         1.0         0.0       1.0  
1         1.0         0.0       1.0  
2         1.0         0.0       1.0  
3         0.0         0.0       1.0  
4         0.0         1.0       0.0  

[5 rows x 46 columns]

In [12]:
dummy.head()

workclass_Federal-gov  workclass_Local-gov  workclass_Private  \
0                    0.0                  0.0                0.0   
1                    0.0                  0.0                0.0   
2                    0.0                  0.0                1.0   
3                    0.0                  0.0                1.0   
4                    0.0                  0.0                1.0   

   workclass_Self-emp-inc  workclass_Self-emp-not-inc  workclass_State-gov  \
0                     0.0                         0.0                  1.0   
1                     0.0                         1.0                  0.0   
2                     0.0                         0.0                  0.0   
3                     0.0                         0.0                  0.0   
4                     0.0                         0.0                  0.0   

   workclass_Without-pay  marital_Divorced  marital_Married-AF-spouse  \
0                    0.0               0.0                        0.0   
1                    0.0               0.0                        0.0   
2                    0.0               1.0                        0.0   
3                    0.0               0.0                        0.0   
4                    0.0               0.0                        0.0   

   marital_Married-civ-spouse    ...     relationship_Own-child  \
0                         0.0    ...                        0.0   
1                         1.0    ...                        0.0   
2                         0.0    ...                        0.0   
3                         1.0    ...                        0.0   
4                         1.0    ...                        0.0   

   relationship_Unmarried  relationship_Wife  race_Amer-Indian-Eskimo  \
0                     0.0                0.0                      0.0   
1                     0.0                0.0                      0.0   
2                     0.0                0.0                      0.0   
3                     0.0                0.0                      0.0   
4                     0.0                1.0                      0.0   

   race_Asian-Pac-Islander  race_Black  race_Other  race_White  sex_Female  \
0                      0.0         0.0         0.0         1.0         0.0   
1                      0.0         0.0         0.0         1.0         0.0   
2                      0.0         0.0         0.0         1.0         0.0   
3                      0.0         1.0         0.0         0.0         0.0   
4                      0.0         1.0         0.0         0.0         1.0   

   sex_Male  
0       1.0  
1       1.0  
2       1.0  
3       1.0  
4       0.0  

[5 rows x 41 columns]

## 종속변수

In [13]:
dep = train.columns[-1]
y = train[dep]

In [14]:
y.head()

0    under50k
1    under50k
2    under50k
3    under50k
4    under50k
Name: income, dtype: object

## 변수 형태에 따른 데이터 분할 

#### 범주형 

In [15]:
train[discrete].head()

workclass             marital         occupation   relationship  \
0         State-gov       Never-married       Adm-clerical  Not-in-family   
1  Self-emp-not-inc  Married-civ-spouse    Exec-managerial        Husband   
2           Private            Divorced  Handlers-cleaners  Not-in-family   
3           Private  Married-civ-spouse  Handlers-cleaners        Husband   
4           Private  Married-civ-spouse     Prof-specialty           Wife   

    race     sex  
0  White    Male  
1  White    Male  
2  White    Male  
3  Black    Male  
4  Black  Female

In [16]:
discrete_X = train[discrete]

In [17]:
train[continuous].head()

age  education  capital_gain  capital_loss  hours_per_week
0   39         13          2174             0              40
1   50         13             0             0              13
2   38          9             0             0              40
3   53          7             0             0              40
4   28         13             0             0              40

In [18]:
continuous_X = train[continuous]

## 데이터 분할

In [19]:
from sklearn.model_selection import train_test_split

In [20]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=0)

In [21]:
X_discrete_train, X_discrete_test, y_discrete_train, y_discrete_test = train_test_split(discrete_X, y, test_size=0.1, random_state=0)

In [22]:
X_continuous_train, X_continuous_test, y_continuous_train, y_continuous_test = train_test_split(continuous_X, y, test_size=0.1, random_state=0)

## Import library

In [23]:
from sklearn.linear_model import LogisticRegression

In [24]:
from sklearn import metrics

### 기준점 Lasso (교수님)
    [[ 376  253]
     [ 125 1746]]
    accuracy: 0.8488
    precision: 0.750499001996
    recall: 0.597774244833
    f1: 0.665486725664

### Get_Result(y_test, y_pred)

In [25]:
def getResult(y_test,y_pred):
    print(metrics.confusion_matrix(y_test, y_pred))
    print('accurracy:', metrics.accuracy_score(y_test, y_pred))
    print('precision:', metrics.precision_score(y_test, y_pred, pos_label='over50k'))
    print('recall:', metrics.recall_score(y_test, y_pred, pos_label='over50k'))
    print('f1:', metrics.f1_score(y_test, y_pred, pos_label='over50k'))

## Logistic Regression : ridge

 - 전체 버젼

In [26]:
ridge = LogisticRegression(penalty='l2',C=15)

In [27]:
ridge.fit(X_train,y_train)

LogisticRegression(C=15, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [28]:
y_ridge = ridge.predict(X_test)

In [29]:
metrics.confusion_matrix(y_test,y_ridge)

array([[ 374,  255],
       [ 124, 1747]])

In [30]:
getResult(y_test,y_ridge)

[[ 374  255]
 [ 124 1747]]
accurracy: 0.8484
precision: 0.751004016064
recall: 0.594594594595
f1: 0.663708961846


In [38]:
def logi(x,y):
    LR = LogisticRegression(penalty=x,C=y)
    LR.fit(X_train,y_train)
    y_ridge = LR.predict(X_test)
    getResult(y_test,y_ridge)
    return LR

        10 l1
        [[ 380  249]
         [ 129 1742]]
        accurracy: 0.8488
        precision: 0.746561886051
        recall: 0.60413354531
        f1: 0.66783831283

In [40]:
logistic = []
penal = ['l1','l2']
for i in range(10,100,5):
    for j in penal:
        print(i,j)
        logistic.append(logi(j,i))

10 l1
[[ 380  249]
 [ 129 1742]]
accurracy: 0.8488
precision: 0.746561886051
recall: 0.60413354531
f1: 0.66783831283
10 l2
[[ 375  254]
 [ 124 1747]]
accurracy: 0.8488
precision: 0.751503006012
recall: 0.596184419714
f1: 0.664893617021
15 l1
[[ 380  249]
 [ 129 1742]]
accurracy: 0.8488
precision: 0.746561886051
recall: 0.60413354531
f1: 0.66783831283
15 l2
[[ 374  255]
 [ 124 1747]]
accurracy: 0.8484
precision: 0.751004016064
recall: 0.594594594595
f1: 0.663708961846
20 l1
[[ 379  250]
 [ 129 1742]]
accurracy: 0.8484
precision: 0.746062992126
recall: 0.602543720191
f1: 0.666666666667
20 l2
[[ 375  254]
 [ 124 1747]]
accurracy: 0.8488
precision: 0.751503006012
recall: 0.596184419714
f1: 0.664893617021
25 l1
[[ 380  249]
 [ 129 1742]]
accurracy: 0.8488
precision: 0.746561886051
recall: 0.60413354531
f1: 0.66783831283
25 l2
[[ 377  252]
 [ 127 1744]]
accurracy: 0.8484
precision: 0.748015873016
recall: 0.599364069952
f1: 0.665489849956
30 l1
[[ 379  250]
 [ 129 1742]]
accurracy: 0.8484
pre

 - 이산형 버젼 

In [31]:
ridge_l2 = LogisticRegression(penalty='l2',C=15)

In [32]:
ridge_l2.fit(X_continuous_train,y_continuous_train)

LogisticRegression(C=15, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [33]:
y_continuous_ridge = ridge_l2.predict(X_continuous_test)

In [34]:
getResult(y_continuous_test,y_continuous_ridge)

[[ 234  395]
 [  77 1794]]
accurracy: 0.8112
precision: 0.752411575563
recall: 0.372019077901
f1: 0.497872340426


# Decision Tree
## Random Forest (랜덤포레스트)

In [44]:
from sklearn.ensemble import RandomForestClassifier

In [36]:
rf = RandomForestClassifier(n_estimators=100)

In [37]:
rf.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            n_estimators=100, n_jobs=1, oob_score=False, random_state=None,
            verbose=0, warm_start=False)

In [38]:
y_rf = rf.predict(X_test)

In [39]:
getResult(y_test,y_rf)

[[ 390  239]
 [ 153 1718]]
accurracy: 0.8432
precision: 0.718232044199
recall: 0.620031796502
f1: 0.665529010239


In [41]:
def randomLoop(x):
    print(x)
    rf = RandomForestClassifier(n_estimators=100)
    rf.fit(X_train,y_train)
    y_rf = rf.predict(X_test)
    getResult(y_test,y_rf)
    return rf

In [42]:
RF = []

In [45]:
for i in range(100,1000,100):
    RF.append(randomLoop(i))

100
[[ 394  235]
 [ 156 1715]]
accurracy: 0.8436
precision: 0.716363636364
recall: 0.626391096979
f1: 0.668363019508
200
[[ 396  233]
 [ 159 1712]]
accurracy: 0.8432
precision: 0.713513513514
recall: 0.629570747218
f1: 0.668918918919
300
[[ 394  235]
 [ 152 1719]]
accurracy: 0.8452
precision: 0.721611721612
recall: 0.626391096979
f1: 0.670638297872
400
[[ 393  236]
 [ 157 1714]]
accurracy: 0.8428
precision: 0.714545454545
recall: 0.62480127186
f1: 0.666666666667
500
[[ 392  237]
 [ 153 1718]]
accurracy: 0.844
precision: 0.719266055046
recall: 0.623211446741
f1: 0.667802385009
600
[[ 395  234]
 [ 156 1715]]
accurracy: 0.844
precision: 0.716878402904
recall: 0.627980922099
f1: 0.669491525424
700
[[ 395  234]
 [ 156 1715]]
accurracy: 0.844
precision: 0.716878402904
recall: 0.627980922099
f1: 0.669491525424
800
[[ 394  235]
 [ 159 1712]]
accurracy: 0.8424
precision: 0.712477396022
recall: 0.626391096979
f1: 0.666666666667
900
[[ 393  236]
 [ 160 1711]]
accurracy: 0.8416
precision: 0.710669

 - 이산형

In [40]:
rf.fit(X_continuous_train,y_continuous_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            n_estimators=100, n_jobs=1, oob_score=False, random_state=None,
            verbose=0, warm_start=False)

In [41]:
y_rf = rf.predict(X_continuous_test)

In [42]:
getResult(y_continuous_test,y_rf)

[[ 306  323]
 [ 150 1721]]
accurracy: 0.8108
precision: 0.671052631579
recall: 0.486486486486
f1: 0.564055299539


## Gradient Boosting Tree

In [47]:
from sklearn.ensemble import GradientBoostingClassifier

In [52]:
gb = GradientBoostingClassifier(n_estimators=15)

In [53]:
gb.fit(X_train,y_train)

GradientBoostingClassifier(criterion='friedman_mse', init=None,
              learning_rate=0.1, loss='deviance', max_depth=3,
              max_features=None, max_leaf_nodes=None,
              min_impurity_split=1e-07, min_samples_leaf=1,
              min_samples_split=2, min_weight_fraction_leaf=0.0,
              n_estimators=15, presort='auto', random_state=None,
              subsample=1.0, verbose=0, warm_start=False)

In [54]:
y_gb = gb.predict(X_test)

In [55]:
getResult(y_test,y_gb)

[[ 304  325]
 [  80 1791]]
accurracy: 0.838
precision: 0.791666666667
recall: 0.483306836248
f1: 0.600197433366


In [46]:
def gbt(x):
    gb = GradientBoostingClassifier(n_estimators=x)
    gb.fit(X_train,y_train)
    y_gb = gb.predict(X_test)
    getResult(y_test,y_gb)
    return gb

In [48]:
gb_list = []

In [50]:
for i in range(50,100,5):
    print(i)
    gb_list.append(gbt(i))

50
[[ 353  276]
 [  93 1778]]
accurracy: 0.8524
precision: 0.791479820628
recall: 0.561208267091
f1: 0.656744186047
55
[[ 358  271]
 [  94 1777]]
accurracy: 0.854
precision: 0.79203539823
recall: 0.569157392687
f1: 0.662349676226
60
[[ 365  264]
 [  94 1777]]
accurracy: 0.8568
precision: 0.795206971678
recall: 0.580286168521
f1: 0.670955882353
65
[[ 369  260]
 [  95 1776]]
accurracy: 0.858
precision: 0.79525862069
recall: 0.586645468998
f1: 0.675205855444
70
[[ 372  257]
 [  96 1775]]
accurracy: 0.8588
precision: 0.794871794872
recall: 0.591414944356
f1: 0.678213309025
75
[[ 371  258]
 [  96 1775]]
accurracy: 0.8584
precision: 0.79443254818
recall: 0.589825119237
f1: 0.67700729927
80
[[ 376  253]
 [  96 1775]]
accurracy: 0.8604
precision: 0.796610169492
recall: 0.597774244833
f1: 0.683015440509
85
[[ 376  253]
 [  96 1775]]
accurracy: 0.8604
precision: 0.796610169492
recall: 0.597774244833
f1: 0.683015440509
90
[[ 378  251]
 [  99 1772]]
accurracy: 0.86
precision: 0.792452830189
recall

## SVM

In [56]:
from sklearn.svm import SVC

In [68]:
model = SVC(kernel='rbf',C=5,cache_size=1000)
model.fit(X_train, y_train)

SVC(C=5, cache_size=1000, class_weight=None, coef0=0.0,
  decision_function_shape=None, degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [69]:
y_pred = model.predict(X_test)

In [70]:
getResult(y_test,y_pred)

[[ 387  242]
 [ 103 1768]]
accurracy: 0.862
precision: 0.789795918367
recall: 0.615262321145
f1: 0.691689008043


In [71]:
def run_model(kernel,penalty,cache):
    model = SVC(kernel=kernel, C=penalty,cache_size=cache)
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    
    getResult(y_test,y_pred)
    return model

In [72]:
svc = run_model('rbf',10,1000)

[[ 397  232]
 [ 119 1752]]
accurracy: 0.8596
precision: 0.769379844961
recall: 0.631160572337
f1: 0.693449781659


In [78]:
a = []

In [82]:
for i in range(1,10):
    s = run_model('rbf',i,1000)
    a.append(s)

[[ 335  294]
 [  81 1790]]
accurracy: 0.85
precision: 0.805288461538
recall: 0.532591414944
f1: 0.641148325359
[[ 352  277]
 [  90 1781]]
accurracy: 0.8532
precision: 0.796380090498
recall: 0.559618441971
f1: 0.657329598506
[[ 373  256]
 [  92 1779]]
accurracy: 0.8608
precision: 0.802150537634
recall: 0.593004769475
f1: 0.681901279707
[[ 379  250]
 [ 101 1770]]
accurracy: 0.8596
precision: 0.789583333333
recall: 0.602543720191
f1: 0.68349864743
[[ 387  242]
 [ 103 1768]]
accurracy: 0.862
precision: 0.789795918367
recall: 0.615262321145
f1: 0.691689008043
[[ 393  236]
 [ 108 1763]]
accurracy: 0.8624
precision: 0.784431137725
recall: 0.62480127186
f1: 0.695575221239
[[ 393  236]
 [ 113 1758]]
accurracy: 0.8604
precision: 0.776679841897
recall: 0.62480127186
f1: 0.692511013216
[[ 395  234]
 [ 116 1755]]
accurracy: 0.86
precision: 0.772994129159
recall: 0.627980922099
f1: 0.69298245614
[[ 396  233]
 [ 116 1755]]
accurracy: 0.8604
precision: 0.7734375
recall: 0.629570747218
f1: 0.6941279579

### SVM 
 - c = 6 일때 가장 높았다 
         [[ 393  236]
         [ 108 1763]]
        accurracy: 0.8624
        precision: 0.784431137725
        recall: 0.62480127186
        f1: 0.695575221239

In [84]:
b = []

In [85]:
for i in range(10,15):
    print(i)
    s = run_model('rbf',i,2000)
    b.append(s)

10
[[ 397  232]
 [ 119 1752]]
accurracy: 0.8596
precision: 0.769379844961
recall: 0.631160572337
f1: 0.693449781659
11
[[ 397  232]
 [ 118 1753]]
accurracy: 0.86
precision: 0.770873786408
recall: 0.631160572337
f1: 0.694055944056
12
[[ 399  230]
 [ 121 1750]]
accurracy: 0.8596
precision: 0.767307692308
recall: 0.634340222576
f1: 0.694516971279
13
[[ 399  230]
 [ 123 1748]]
accurracy: 0.8588
precision: 0.764367816092
recall: 0.634340222576
f1: 0.693310165074
14
[[ 401  228]
 [ 124 1747]]
accurracy: 0.8592
precision: 0.76380952381
recall: 0.637519872814
f1: 0.694974003466


In [86]:
c = []

In [ ]:
for i in range(1,15):
    print(i)
    s = run_model('linear',i,2000)
    c.append(s)

1


### SVM 커널 

In [ ]:
data = train[discrete]
data.head()

In [ ]:
X = data[[x for x in discrete]]

In [ ]:
y.head()

In [ ]:
def hand_made_kernel(d1, d2):
    same = 0
    for a, b in zip(d1, d2):
        if a == b:
            same = same + 1
    return same

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4)

In [ ]:
row_train, _ = X_train.shape

In [ ]:
row_train

In [ ]:
import numpy

In [ ]:
P_train = numpy.zeros((row_train, row_train))

In [ ]:
for i in range(row_train):
    if i % 1000 == 0:
        print(i)
    for j in range(row_train):
        P_train[i, j] = hand_made_kernel(X_train.iloc[i,:], X_train.iloc[j,:])

In [ ]:
P_train

### 훈련

In [ ]:
model = SVC(kernel='precomputed', C=1)

In [ ]:
model.fit(P_train, y_train)

In [ ]:
row_test, _ = X_test.shape

In [ ]:
row_test

In [ ]:
row_train

In [ ]:
P_test = numpy.zeros((row_test, row_train))

In [ ]:
for i in range(row_test):
    for j in range(row_train):
        P_test[i, j] = hand_made_kernel(X_test.iloc[i,:], X_train.iloc[j,:])

In [ ]:
P_test

In [ ]:
yp = model.predict(P_test)

In [ ]:
getResult(y_test,yp)