# Final Test (Classification)

## 데이터 불러오기

In [1]:
import pandas as pd

In [2]:
train = pd.read_csv('train.csv')

In [3]:
train.head()

age         workclass  education             marital         occupation  \
0   39         State-gov         13       Never-married       Adm-clerical   
1   50  Self-emp-not-inc         13  Married-civ-spouse    Exec-managerial   
2   38           Private          9            Divorced  Handlers-cleaners   
3   53           Private          7  Married-civ-spouse  Handlers-cleaners   
4   28           Private         13  Married-civ-spouse     Prof-specialty   

    relationship   race     sex  capital_gain  capital_loss  hours_per_week  \
0  Not-in-family  White    Male          2174             0              40   
1        Husband  White    Male             0             0              13   
2  Not-in-family  White    Male             0             0              40   
3        Husband  Black    Male             0             0              40   
4           Wife  Black  Female             0             0              40   

     income  
0  under50k  
1  under50k  
2  under50k  
3  under50k  
4  under50k

In [4]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24999 entries, 0 to 24998
Data columns (total 12 columns):
age               24999 non-null int64
workclass         24999 non-null object
education         24999 non-null int64
marital           24999 non-null object
occupation        24999 non-null object
relationship      24999 non-null object
race              24999 non-null object
sex               24999 non-null object
capital_gain      24999 non-null int64
capital_loss      24999 non-null int64
hours_per_week    24999 non-null int64
income            24999 non-null object
dtypes: int64(5), object(7)
memory usage: 2.3+ MB


## 독립변수

In [5]:
train.columns

Index(['age', 'workclass', 'education', 'marital', 'occupation',
       'relationship', 'race', 'sex', 'capital_gain', 'capital_loss',
       'hours_per_week', 'income'],
      dtype='object')

In [6]:
indep = train.columns[:-1]

In [7]:
discrete = []
continuous = []
for v in indep:
    if train[v].dtype == 'object':
        discrete.append(v)
    else:
        continuous.append(v)

In [8]:
discrete

['workclass', 'marital', 'occupation', 'relationship', 'race', 'sex']

In [9]:
continuous

['age', 'education', 'capital_gain', 'capital_loss', 'hours_per_week']

In [10]:
dummy = pd.get_dummies(train[discrete])
X = pd.concat([train[continuous], dummy], axis=1)

In [11]:
X.head()

age  education  capital_gain  capital_loss  hours_per_week  \
0   39         13          2174             0              40   
1   50         13             0             0              13   
2   38          9             0             0              40   
3   53          7             0             0              40   
4   28         13             0             0              40   

   workclass_Federal-gov  workclass_Local-gov  workclass_Private  \
0                    0.0                  0.0                0.0   
1                    0.0                  0.0                0.0   
2                    0.0                  0.0                1.0   
3                    0.0                  0.0                1.0   
4                    0.0                  0.0                1.0   

   workclass_Self-emp-inc  workclass_Self-emp-not-inc    ...     \
0                     0.0                         0.0    ...      
1                     0.0                         1.0    ...      
2                     0.0                         0.0    ...      
3                     0.0                         0.0    ...      
4                     0.0                         0.0    ...      

   relationship_Own-child  relationship_Unmarried  relationship_Wife  \
0                     0.0                     0.0                0.0   
1                     0.0                     0.0                0.0   
2                     0.0                     0.0                0.0   
3                     0.0                     0.0                0.0   
4                     0.0                     0.0                1.0   

   race_Amer-Indian-Eskimo  race_Asian-Pac-Islander  race_Black  race_Other  \
0                      0.0                      0.0         0.0         0.0   
1                      0.0                      0.0         0.0         0.0   
2                      0.0                      0.0         0.0         0.0   
3                      0.0                      0.0         1.0         0.0   
4                      0.0                      0.0         1.0         0.0   

   race_White  sex_Female  sex_Male  
0         1.0         0.0       1.0  
1         1.0         0.0       1.0  
2         1.0         0.0       1.0  
3         0.0         0.0       1.0  
4         0.0         1.0       0.0  

[5 rows x 46 columns]

In [12]:
dummy.head()

workclass_Federal-gov  workclass_Local-gov  workclass_Private  \
0                    0.0                  0.0                0.0   
1                    0.0                  0.0                0.0   
2                    0.0                  0.0                1.0   
3                    0.0                  0.0                1.0   
4                    0.0                  0.0                1.0   

   workclass_Self-emp-inc  workclass_Self-emp-not-inc  workclass_State-gov  \
0                     0.0                         0.0                  1.0   
1                     0.0                         1.0                  0.0   
2                     0.0                         0.0                  0.0   
3                     0.0                         0.0                  0.0   
4                     0.0                         0.0                  0.0   

   workclass_Without-pay  marital_Divorced  marital_Married-AF-spouse  \
0                    0.0               0.0                        0.0   
1                    0.0               0.0                        0.0   
2                    0.0               1.0                        0.0   
3                    0.0               0.0                        0.0   
4                    0.0               0.0                        0.0   

   marital_Married-civ-spouse    ...     relationship_Own-child  \
0                         0.0    ...                        0.0   
1                         1.0    ...                        0.0   
2                         0.0    ...                        0.0   
3                         1.0    ...                        0.0   
4                         1.0    ...                        0.0   

   relationship_Unmarried  relationship_Wife  race_Amer-Indian-Eskimo  \
0                     0.0                0.0                      0.0   
1                     0.0                0.0                      0.0   
2                     0.0                0.0                      0.0   
3                     0.0                0.0                      0.0   
4                     0.0                1.0                      0.0   

   race_Asian-Pac-Islander  race_Black  race_Other  race_White  sex_Female  \
0                      0.0         0.0         0.0         1.0         0.0   
1                      0.0         0.0         0.0         1.0         0.0   
2                      0.0         0.0         0.0         1.0         0.0   
3                      0.0         1.0         0.0         0.0         0.0   
4                      0.0         1.0         0.0         0.0         1.0   

   sex_Male  
0       1.0  
1       1.0  
2       1.0  
3       1.0  
4       0.0  

[5 rows x 41 columns]

## 종속변수

In [13]:
dep = train.columns[-1]
y = train[dep]

In [14]:
y.head()

0    under50k
1    under50k
2    under50k
3    under50k
4    under50k
Name: income, dtype: object

## 변수 형태에 따른 데이터 분할 

#### 범주형 

In [16]:
train[discrete].head()

workclass             marital         occupation   relationship  \
0         State-gov       Never-married       Adm-clerical  Not-in-family   
1  Self-emp-not-inc  Married-civ-spouse    Exec-managerial        Husband   
2           Private            Divorced  Handlers-cleaners  Not-in-family   
3           Private  Married-civ-spouse  Handlers-cleaners        Husband   
4           Private  Married-civ-spouse     Prof-specialty           Wife   

    race     sex  
0  White    Male  
1  White    Male  
2  White    Male  
3  Black    Male  
4  Black  Female

In [17]:
discrete_X = train[discrete]

In [20]:
train[continuous].head()

age  education  capital_gain  capital_loss  hours_per_week
0   39         13          2174             0              40
1   50         13             0             0              13
2   38          9             0             0              40
3   53          7             0             0              40
4   28         13             0             0              40

In [21]:
continuous_X = train[continuous]

## 데이터 분할

In [23]:
from sklearn.model_selection import train_test_split

In [24]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=0)

In [25]:
X_discrete_train, X_discrete_test, y_discrete_train, y_discrete_test = train_test_split(discrete_X, y, test_size=0.1, random_state=0)

In [26]:
X_continuous_train, X_continuous_test, y_continuous_train, y_continuous_test = train_test_split(continuous_X, y, test_size=0.1, random_state=0)

## Import library

In [28]:
from sklearn.linear_model import LogisticRegression

In [30]:
from sklearn import metrics

### 기준점 Lasso (교수님)
    [[ 376  253]
     [ 125 1746]]
    accuracy: 0.8488
    precision: 0.750499001996
    recall: 0.597774244833
    f1: 0.665486725664

### Get_Result(y_test, y_pred)

In [31]:
def getResult(y_test,y_pred):
    print(metrics.confusion_matrix(y_test, y_pred))
    print('accurracy:', metrics.accuracy_score(y_test, y_pred))
    print('precision:', metrics.precision_score(y_test, y_pred, pos_label='over50k'))
    print('recall:', metrics.recall_score(y_test, y_pred, pos_label='over50k'))
    print('f1:', metrics.f1_score(y_test, y_pred, pos_label='over50k'))

## Logistic Regression : ridge

 - 전체 버젼

In [56]:
ridge = LogisticRegression(penalty='l2',C=15)

In [57]:
ridge.fit(X_train,y_train)

LogisticRegression(C=15, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [58]:
y_ridge = ridge.predict(X_test)

In [59]:
metrics.confusion_matrix(y_test,y_ridge)

array([[ 374,  255],
       [ 124, 1747]])

In [60]:
getResult(y_test,y_ridge)

[[ 374  255]
 [ 124 1747]]
accurracy: 0.8484
precision: 0.751004016064
recall: 0.594594594595
f1: 0.663708961846


 - 이산형 버젼 

In [47]:
ridge_l2 = LogisticRegression(penalty='l2',C=15)

In [48]:
ridge_l2.fit(X_continuous_train,y_continuous_train)

LogisticRegression(C=15, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [49]:
y_continuous_ridge = ridge_l2.predict(X_continuous_test)

In [50]:
getResult(y_continuous_test,y_continuous_ridge)

[[ 234  395]
 [  77 1794]]
accurracy: 0.8112
precision: 0.752411575563
recall: 0.372019077901
f1: 0.497872340426


# Decision Tree
## Random Forest (랜덤포레스트)

In [61]:
from sklearn.ensemble import RandomForestClassifier

In [62]:
rf = RandomForestClassifier(n_estimators=100)

In [63]:
rf.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            n_estimators=100, n_jobs=1, oob_score=False, random_state=None,
            verbose=0, warm_start=False)

In [64]:
y_rf = rf.predict(X_test)

In [65]:
getResult(y_test,y_rf)

[[ 392  237]
 [ 155 1716]]
accurracy: 0.8432
precision: 0.716636197441
recall: 0.623211446741
f1: 0.666666666667


 - 이산형

In [66]:
rf.fit(X_continuous_train,y_continuous_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            n_estimators=100, n_jobs=1, oob_score=False, random_state=None,
            verbose=0, warm_start=False)

In [67]:
y_rf = rf.predict(X_continuous_test)

In [68]:
getResult(y_continuous_test,y_rf)

[[ 304  325]
 [ 149 1722]]
accurracy: 0.8104
precision: 0.671081677704
recall: 0.483306836248
f1: 0.561922365989


 - 범주형

In [69]:
rf.fit(X_discrete_train,y_discrete_train)

ValueError: could not convert string to float: 'Male'

## Gradient Boosting Tree

In [30]:
from sklearn.ensemble import GradientBoostingClassifier

In [31]:
gb = GradientBoostingClassifier(n_estimators=15)

In [32]:
gb.fit(X_train,y_train)

GradientBoostingClassifier(criterion='friedman_mse', init=None,
              learning_rate=0.1, loss='deviance', max_depth=3,
              max_features=None, max_leaf_nodes=None,
              min_impurity_split=1e-07, min_samples_leaf=1,
              min_samples_split=2, min_weight_fraction_leaf=0.0,
              n_estimators=15, presort='auto', random_state=None,
              subsample=1.0, verbose=0, warm_start=False)

In [33]:
y_gb = gb.predict(X_test)

In [34]:
getResult(y_test,y_gb)

[[ 304  325]
 [  80 1791]]
accurracy: 0.838
precision: 0.791666666667
recall: 0.483306836248
f1: 0.600197433366


## SVM

In [35]:
from sklearn.svm import SVC

In [36]:
model = SVC(kernel='rbf',C=0.1)
model.fit(X_train, y_train)

SVC(C=0.1, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape=None, degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [37]:
y_pred = model.predict(X_test)

In [38]:
getResult(y_test,y_pred)

[[ 239  390]
 [  50 1821]]
accurracy: 0.824
precision: 0.826989619377
recall: 0.379968203498
f1: 0.520697167756


In [39]:
y_pred

array(['under50k', 'under50k', 'under50k', ..., 'under50k', 'under50k',
       'under50k'], dtype=object)

### SVM 커널 

In [40]:
data = train[discrete]
data.head()

workclass             marital         occupation   relationship  \
0         State-gov       Never-married       Adm-clerical  Not-in-family   
1  Self-emp-not-inc  Married-civ-spouse    Exec-managerial        Husband   
2           Private            Divorced  Handlers-cleaners  Not-in-family   
3           Private  Married-civ-spouse  Handlers-cleaners        Husband   
4           Private  Married-civ-spouse     Prof-specialty           Wife   

    race     sex  
0  White    Male  
1  White    Male  
2  White    Male  
3  Black    Male  
4  Black  Female

In [41]:
X = data[[x for x in discrete]]

In [42]:
y.head()

0    under50k
1    under50k
2    under50k
3    under50k
4    under50k
Name: income, dtype: object

In [56]:
def hand_made_kernel(d1, d2):
    same = 0
    for a, b in zip(d1, d2):
        if a == b:
            same = same + 1
    return same

In [50]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4)

In [51]:
row_train, _ = X_train.shape

In [52]:
row_train

14999

In [53]:
import numpy

In [54]:
P_train = numpy.zeros((row_train, row_train))

In [ ]:
for i in range(row_train):
    if i % 1000 == 0:
        print(i)
    for j in range(row_train):
        P_train[i, j] = hand_made_kernel(X_train.iloc[i,:], X_train.iloc[j,:])

0


In [ ]:
P_train

### 훈련

In [ ]:
model = SVC(kernel='precomputed', C=1)

In [ ]:
model.fit(P_train, y_train)

In [ ]:
row_test, _ = X_test.shape

In [ ]:
row_test

In [ ]:
row_train

In [ ]:
P_test = numpy.zeros((row_test, row_train))

In [ ]:
for i in range(row_test):
    for j in range(row_train):
        P_test[i, j] = hand_made_kernel(X_test.iloc[i,:], X_train.iloc[j,:])

In [ ]:
P_test

In [ ]:
yp = model.predict(P_test)

In [ ]:
getResult(y_test,yp)