# Multi-variable Linear Regression

In [28]:
import tensorflow as tf
import numpy as np

### Data set

In [5]:
x1_data = [1,0,3,0,5]
x2_data = [0,2,0,4,0]
y_data = [1,2,3,4,5]

### find values for W and b that comput y_data = W * x_data + b

In [11]:
W1 = tf.Variable(tf.random_uniform([1],-1.0,1.0)) # -1.0 ~ 1.0의 난수
W2 = tf.Variable(tf.random_uniform([1],-1.0,1.0)) # -1.0 ~ 1.0의 난수
b = tf.Variable(tf.random_uniform([1],-1.0,1.0))

### Hypothesis

In [12]:
hypothesis = W1 * x1_data + W2 * x2_data + b

### Simplified cost function
 - $\sum_{i=1}^m(W_x^{(i)}-y^{(i)})^2$

In [13]:
cost = tf.reduce_mean(tf.square(hypothesis-y_data))

### Minimize 

In [14]:
a = tf.Variable(0.1)  # learning rate, alpha
optimizer = tf.train.GradientDescentOptimizer(a)
train = optimizer.minimize(cost)  # goal is minimize cost

### Initialize the variables & Launch

In [16]:
init = tf.initialize_all_variables()

sess = tf.Session()
sess.run(init)

for step in range(2001):
    sess.run(train)
    if step % 20 == 0:
        print(step, sess.run(cost), sess.run(W1),sess.run(W2),sess.run(b))

0 0.097711 [ 0.95223987] [ 0.82589006] [ 0.51273668]
20 0.0127219 [ 0.92971146] [ 0.91660309] [ 0.26738739]
40 0.00368353 [ 0.96217835] [ 0.95512486] [ 0.14387882]
60 0.00106654 [ 0.97964853] [ 0.97585309] [ 0.07741997]
80 0.000308808 [ 0.98904902] [ 0.98700672] [ 0.04165902]
100 8.94124e-05 [ 0.99410743] [ 0.99300843] [ 0.02241634]
120 2.58883e-05 [ 0.99682921] [ 0.99623793] [ 0.012062]
140 7.49597e-06 [ 0.99829382] [ 0.99797565] [ 0.00649043]
160 2.17044e-06 [ 0.99908185] [ 0.99891073] [ 0.00349241]
180 6.28464e-07 [ 0.99950594] [ 0.99941385] [ 0.00187924]
200 1.81967e-07 [ 0.99973416] [ 0.99968457] [ 0.00101119]
220 5.26809e-08 [ 0.99985701] [ 0.99983031] [ 0.00054414]
240 1.52612e-08 [ 0.99992305] [ 0.99990869] [ 0.00029278]
260 4.41597e-09 [ 0.99995857] [ 0.99995083] [ 0.00015754]
280 1.27878e-09 [ 0.99997777] [ 0.99997354] [  8.47936462e-05]
300 3.70267e-10 [ 0.99998802] [ 0.99998575] [  4.56215930e-05]
320 1.06718e-10 [ 0.9999935] [ 0.99999237] [  2.45645315e-05]
340 3.06386e-11

## Matrix Multiplication
 <img src="photo/2.PNG" width=600 align="left">

In [17]:
xy = np.loadtxt('03train.txt', unpack=True, dtype='float32')
x_data = xy[0:-1]
y_data = xy[-1]

In [22]:
print(x_data)
print(y_data)

[[ 1.  1.  1.  1.  1.]
 [ 1.  0.  3.  0.  5.]
 [ 0.  2.  0.  4.  0.]]
[ 1.  2.  3.  4.  5.]


## x_data 에서 1열이 전체 1이 되는 이유는 ???
 <img src="photo/1.PNG" width=600>
 
 - 위와 같은 형태로 간단하게 표현이 가능하도록 하기 위해서 

In [30]:
x_data.T

array([[ 1.,  1.,  0.],
       [ 1.,  0.,  2.],
       [ 1.,  3.,  0.],
       [ 1.,  0.,  4.],
       [ 1.,  5.,  0.]], dtype=float32)

In [31]:
W = tf.Variable(tf.random_uniform([1, len(x_data)], -1, 1)) # len(x_data) -> [1,3] 으로 생성하여 마지막에 b와 x_data의 1열과 행렬곱
b = tf.Variable(tf.random_uniform([1], -1, 1))

 - matmul : Matrix Multiplication

In [25]:
hypothesis = tf.matmul(W, x_data)

In [26]:
cost = tf.reduce_mean(tf.square(hypothesis - y_data))

a = tf.Variable(0.1)  # learning rate, alpha
optimizer = tf.train.GradientDescentOptimizer(a)
train = optimizer.minimize(cost)  # goal is minimize cost

init = tf.initialize_all_variables()

sess = tf.Session()
sess.run(init)

for step in range(2001):
    sess.run(train)
    if step % 20 == 0:
        print(step, sess.run(cost), sess.run(W))

0 0.803903 [[ 0.88463748  1.08051205  0.75241399]]
20 0.0335119 [[ 0.43397462  0.88592076  0.86464536]]
40 0.00970309 [[ 0.233518    0.93861473  0.92716682]]
60 0.00280946 [[ 0.12565401  0.96696913  0.96080911]]
80 0.000813456 [[ 0.06761331  0.98222643  0.9789117 ]]
100 0.00023553 [[ 0.03638211  0.9904362   0.98865259]]
120 6.81962e-05 [[ 0.01957692  0.99485379  0.99389404]]
140 1.97458e-05 [[ 0.0105342   0.99723095  0.99671441]]
160 5.71716e-06 [[ 0.00566835  0.99850994  0.99823207]]
180 1.65535e-06 [[ 0.00305005  0.99919814  0.99904865]]
200 4.79342e-07 [[ 0.00164123  0.99956858  0.99948806]]
220 1.3879e-07 [[  8.83121160e-04   9.99767780e-01   9.99724567e-01]]
240 4.01892e-08 [[  4.75231005e-04   9.99875069e-01   9.99851763e-01]]
260 1.16416e-08 [[  2.55724444e-04   9.99932826e-01   9.99920249e-01]]
280 3.36368e-09 [[  1.37597948e-04   9.99963820e-01   9.99957085e-01]]
300 9.77923e-10 [[  7.40119140e-05   9.99980569e-01   9.99976933e-01]]
320 2.81705e-10 [[  3.97989352e-05   9.99989