# 7. 코사인 유사도 & Clustering 

In [1]:
from urllib.parse import quote_plus

import requests
import lxml.html

In [2]:
search_url = ('http://section.blog.naver.com/sub/SearchBlog.nhn?type=post&option.keyword={query}'
              '&option.page.currentPage={page}&option.orderBy=sim')

In [3]:
query = quote_plus('딥러닝')
query

'%EB%94%A5%EB%9F%AC%EB%8B%9D'

In [4]:
url = search_url.format(query=query, page=2)
url

'http://section.blog.naver.com/sub/SearchBlog.nhn?type=post&option.keyword=%EB%94%A5%EB%9F%AC%EB%8B%9D&option.page.currentPage=2&option.orderBy=sim'

In [5]:
res = requests.get(url)

In [6]:
root = lxml.html.fromstring(res.text)

In [7]:
root.cssselect('h5 a')

[<Element a at 0x15991ee4f48>,
 <Element a at 0x15991ee4f98>,
 <Element a at 0x15991eee048>,
 <Element a at 0x15991eee098>,
 <Element a at 0x15991eee0e8>,
 <Element a at 0x15991eee138>,
 <Element a at 0x15991eee188>,
 <Element a at 0x15991eee1d8>,
 <Element a at 0x15991eee228>,
 <Element a at 0x15991eee278>]

 - a Class가 존재하지 않는다. 그럴때는 위에 태그를 본다. 

In [8]:
for link in root.cssselect('h5 a'):
    print(link.text_content(), link.attrib['href'])

딥러닝(Deep Learning) 실습과정 강좌 오픈! http://blog.officen.kr/220953268153
AlphaGo(알파고)와 딥러닝 http://blog.naver.com/ysw1130?Redirect=Log&logNo=220653505939&from=section
딥러닝 / 머신러닝 워크스테이션 커스텀수냉은 필수! http://blog.naver.com/digiji1?Redirect=Log&logNo=220822461696&from=section
딥러닝 전망과 응용사례는? http://blog.naver.com/bosungabi?Redirect=Log&logNo=220689269927&from=section
딥러닝 기술로 색깔을 칠해주는, PaintsChainer http://blog.naver.com/jdiycdi?Redirect=Log&logNo=220927019170&from=section
YJ MOD 딥러닝 워크스테이션 http://blog.naver.com/digiji1?Redirect=Log&logNo=220950111651&from=section
6850K 파스칼  타이탄 X 4way 딥러닝 연산용 900D 풀 커스텀 동관 워크스테이션 http://blog.naver.com/polaris_810?Redirect=Log&logNo=220902614790&from=section
알파고 AI 근간이 되는 딥러닝 이야기 http://gamsungit.com/220308660011
GTX1080 4Way 우분투 활용 딥러닝 워크스테이션 http://blog.naver.com/wellmpc?Redirect=Log&logNo=220977799611&from=section
2017 IT트렌드 딥러닝(Deep Lerning) http://blog.naver.com/youhyun4534?Redirect=Log&logNo=220948527326&from=section


## URL 분해
 - 크롤링에서 필요했던 내용들을 분해해서 데이터를 format으로 하면 된다. 

In [9]:
from urllib.parse import parse_qs, urlparse

In [10]:
result = urlparse('http://blog.naver.com/civilize?Redirect=Log&logNo=220976431562&from=section')

In [11]:
result

ParseResult(scheme='http', netloc='blog.naver.com', path='/civilize', params='', query='Redirect=Log&logNo=220976431562&from=section', fragment='')

In [12]:
result.netloc

'blog.naver.com'

In [13]:
result.path

'/civilize'

In [14]:
result.query

'Redirect=Log&logNo=220976431562&from=section'

In [15]:
qs = parse_qs(result.query)
qs

{'Redirect': ['Log'], 'from': ['section'], 'logNo': ['220976431562']}

In [16]:
qs['logNo'][0]

'220976431562'

In [17]:
post_url = 'http://blog.naver.com/PostView.nhn?blogId={}&logNo={}'.format(result.path[1:], qs['logNo'][0])

In [19]:
post_url

'http://blog.naver.com/PostView.nhn?blogId=civilize&logNo=220976431562'

## 게시물 내용 가져오기 

In [20]:
post_res = requests.get(post_url)
post_root = lxml.html.fromstring(post_res.text)

In [21]:
post_root.cssselect('div#postViewArea')[0].text_content()

'\r\n\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\r\n \r\n \r\n  밑바닥부터 시작하는 딥러닝 \r\n  \r\n  작가\r\n  사이토 고키\r\n  출판\r\n  한빛미디어\r\n  발매\r\n  2017.01.03.\r\n  평점\r\n  \r\n   \r\n    \r\n   \r\n  \r\n  \r\n  리뷰보기\r\n \r\n 이런 책이 진작 나왔다면 내가 머신러닝 공부하는데 장벽을 좀 덜 느꼈을텐데 말이다.왜 2017년에서야 나온거냐.일단 책 내용은 요즘 굉장히 핫한 뉴럴넷, 딥러닝을 파이썬으로 구현해 보면서 익히는 것이고,책 제목대로 초짜들도 따라하면서 뉴럴넷의 원리와 필요한 지식들을 배울 수 있게 구성되어 있다.뭐 그래도 calculus, linear algebra 정도는 머릿속에 배경지식을 깔고 들어가야 하고,애초에 머신러닝 분야가 통계나 수학적인 백그라운드 없으면 쉽게 할 수 없으니까그정도는 공부하고 읽는것을 추천한다.근데 난 이 내용 석사때 분명 배우긴 배웠고, matlab으로 구현까지 했던 기억이 있는데하도 손을 놔서 그런지 다 까묵어서 리마인드하는 용도로 보고 있기는 하다.그런 용도로도 괜찮은 책인것도 같고.\r\n\t\t\t\t\t\t\r\n\t\t\t\t\t\t'

## 블로그 스크래핑 

In [22]:
import tqdm
from urllib.parse import urljoin

In [23]:
keyword = '딥러닝'
query = quote_plus(keyword)

In [23]:
search_url = ('http://section.blog.naver.com/sub/SearchBlog.nhn?type=post&option.keyword={query}'
              '&option.page.currentPage={page}&option.orderBy=sim')

In [24]:
posts = []
for page in tqdm.tqdm_notebook(range(1, 20)):
    url = search_url.format(query=query, page=page)
    res = requests.get(url)
    root = lxml.html.fromstring(res.text)
    
    for link in root.cssselect('h5 a'):
        link_url = link.attrib['href']

        # 다른 형식의 주소는 무시
        if not link_url.startswith('http://blog.naver.com'):
            continue

        # 진짜 주소
        result = urlparse(link_url)
        blog_id = result.path[1:]
        qs = parse_qs(result.query)
        post_id = qs['logNo'][0]
        post_url = 'http://blog.naver.com/PostView.nhn?blogId={}&logNo={}'.format(blog_id, post_id)
        
        # 본문 가져오기
        post_res = requests.get(post_url)
        post_root = lxml.html.fromstring(post_res.text)
        
        try:
            body = post_root.cssselect('div#postViewArea')[0]
            posts.append(body.text_content())
        except IndexError:
            continue

In [25]:
len(posts)

83

## CSV로 저장 

In [26]:
import csv
import re 

In [28]:
with open('data/posts.csv', 'w', encoding='utf8', newline='') as f:
    w = csv.writer(f)
    for post in posts:
        post_short = re.sub(r'\s+', ' ', post)  # 모든 종류의 공백을 빈 칸 하나로 바꿈 (엑셀에서 보기 좋게)
        w.writerow([post_short])

## CSV에서 불러오기 

In [29]:
import csv

In [31]:
posts = []
with open("data/posts.csv", encoding="utf8") as f:
    reader = csv.reader(f)
    for row in reader:
        post = row[0]
        if len(post) > 100:
            posts.append(post)

In [32]:
len(posts)

83

In [33]:
posts[:2]

[' 머신러닝의 딥러닝, 미래사회를 이끌다 산업 현장의 지각 변동을 이룰 미래 기술 미국의 IT 리서치 기업 가트너 그룹은 지난 2016년, ITxpo 2016에서 향후 5년간 혁신 잠재력을 지닌 10대 전략기술 트렌드를 발표했다. 가트너가 선정한 2017년 10대 전략 기술은 인텔리전트(Intellegent)와 디지털(Digital), 그리고 메시(Mesh)라는 3가지 영역으로 구분된다. 그중 인공지능과 고급 기계 학습, 즉 머신러닝은 10대 기술의 서두로서 로봇, 자율주행자동차, 가전 기기 등 물리적 디바이스를 비롯해 미래 IT 산업을 선도할 핵심기술로 평가 받고 있다.세상을 바꿀 최고의 전략 기술지난 2016년 ‘ITxpo 2016’에서 미국의 가트너 그룹이 발표한 ‘2017년 10대 전략기술 트렌드’는 향후 5년간 IT 산업 발전을 이끌 10가지 핵심 기술에 대해 이야기한다. 그중 인텔리전트(Intellegent), 즉 지능의 영역으로 분류되는 ‘인공지능과 고급 기계 학습(AI & Advanced Machine Learning)’은 기존의 알고리즘을 넘어 학습 예측, 적응을 비롯해 잠재적으로 스스로 가동하는 자율시스템을 만들어 지능형 스마트 기기를 만든다.인공지능의 한 분야인 머신러닝(Machine Learning)은 데이터의 생성량과 주기, 형식 등 방대한 빅데이터들을 분석해 미래를 예측하는 기술을 말한다. 이 기술은 기존의 빅데이터 분석과 유사점을 지녔지만, 데이터를 수집·분석해 미래를 예측한다는 점에서 차이점을 지녔다. 딥러닝, 신경망, 자연어처리, 첨단기법 등 기술의 결합으로 완성된 머신러닝 기술은 최근 각광받고 있는 물리적 디바이스(로봇, 자율주행자동차 등)을 비롯해 지능형 앱, 메시 디바이스 등 다양한 분야에 적용·융합될 혁신 기술로 평가받는다. 대표적 사례로 글로벌 소셜 네트워크 서비스를 제공하는 페이스북은 ‘Project PANDA’를 통한 딥페이스 기술을 연구한다. 또한, 세계 최대 비디오 스트리밍 기업 넷플릭스는 사용자의 구매 이력을 

## TDM 만들기 

In [34]:
from sklearn.feature_extraction.text import CountVectorizer
from konlpy.tag import Komoran

In [35]:
tagger = Komoran()

In [36]:
def get_noun(text):
    nouns = tagger.nouns(text)
    return [n for n in nouns if len(n) > 1]  # 2글자 이상인 명사만 추출

In [37]:
cv = CountVectorizer(tokenizer=get_noun, max_features=500)

In [38]:
tdm = cv.fit_transform(posts)

In [39]:
tdm # 83개문서를 500개 단어로 생성.

<83x500 sparse matrix of type '<class 'numpy.int64'>'
	with 4594 stored elements in Compressed Sparse Row format>

## TDM 저장 

In [40]:
import numpy as np 

In [41]:
np.savez('data/blog_tdm.npz',tdm)

## 단어 목록 저장 

In [42]:
import json

In [43]:
with open('data/blog_tdm.json', "w", encoding="utf8") as f:
    json.dump(cv.get_feature_names(),f)

## TDM 불러오기 

In [45]:
data = np.load('data/blog_tdm.npz', encoding='latin1')

In [46]:
data.files

['arr_0']

In [47]:
tdm = data['arr_0'].item()

In [48]:
tdm

<83x500 sparse matrix of type '<class 'numpy.int64'>'
	with 4594 stored elements in Compressed Sparse Row format>

## 단어 목록 불러오기 

In [50]:
with open('data/blog_tdm.json', encoding='utf8') as f:
    words = json.load(f)

In [51]:
words[:10]

['가능', '가속', '가이드', '가중치', '가지', '각각', '각종', '감사', '강의', '강좌']

## 차원 축소 

In [52]:
from sklearn.decomposition import TruncatedSVD
from sklearn.preprocessing import Normalizer
from sklearn.pipeline import make_pipeline

In [53]:
svd = TruncatedSVD(n_components=10) # 10개의 차원으로 변경.

In [54]:
svd

TruncatedSVD(algorithm='randomized', n_components=10, n_iter=5,
       random_state=None, tol=0.0)

In [55]:
pos = svd.fit_transform(tdm)

In [56]:
pos.shape

(83, 10)

In [57]:
tdm # 534파일을 500개 단어로 표현 했었다. 그걸 위에서 10개 차원으로 변경 

<83x500 sparse matrix of type '<class 'numpy.int64'>'
	with 4594 stored elements in Compressed Sparse Row format>

In [58]:
pos[0, :]

array([ 41.01439085,  -4.42283017, -11.03644355, -12.43750706,
         3.34100663, -14.78295421,   8.48035465,  -5.37070525,
        16.13714105,  -5.93463435])

## 정규화 
 - 길이도 정보를 가지고 있는데 왜 줄이느냐 라는 비판도 있다.
  - 보통 많이 사용한다. 
  - 다른걸 한다고 해서 크게 좋아지는건 없다...

In [59]:
normalizer = Normalizer(copy=False)
lsa = make_pipeline(svd, normalizer) 
# 연속으로 적용할 수 있도록 svd -> normalizer가 될 수 있도록 

In [60]:
pos = lsa.fit_transform(tdm)

In [61]:
pos.shape

(83, 10)

In [62]:
pos[0, :]

array([ 0.80363434, -0.08666076, -0.21624615, -0.24369955,  0.06546113,
       -0.28970674,  0.16617507, -0.10525595,  0.31657606, -0.11567786])

In [63]:
sum(pos[0, :] ** 2)

1.0000000000000002

## 클러스터링 
 - 1차로 임의의 점으로 cluster 갯수로 해서 가까운 놈들로 나눈다.
 - cluster 에 나누어진 놈들끼리 평균을 구하면 다시 중심을 구할 수 있다.
 - 또 다시 평균을 내서 중심을 잡는다. 
 - 그리고 점들을 중심에서의 거리를 구하고 가까운 놈들에게 포함시키게 한다.
 - 변화가 없을때 까지 돌린다. 

In [64]:
from sklearn.cluster import KMeans

In [65]:
km = KMeans(n_clusters=5)

In [66]:
km.fit(pos)

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
    n_clusters=5, n_init=10, n_jobs=1, precompute_distances='auto',
    random_state=None, tol=0.0001, verbose=0)

In [67]:
km.labels_

array([2, 0, 2, 0, 0, 3, 0, 0, 1, 1, 2, 3, 3, 1, 3, 1, 2, 1, 0, 2, 3, 2, 1,
       0, 2, 0, 3, 2, 3, 1, 1, 3, 0, 3, 0, 0, 3, 4, 1, 1, 4, 0, 2, 0, 0, 4,
       4, 3, 4, 0, 2, 0, 2, 0, 2, 0, 4, 1, 0, 4, 4, 0, 0, 0, 1, 0, 1, 0, 3,
       1, 0, 0, 0, 2, 2, 4, 4, 4, 2, 3, 4, 2, 0])

In [68]:
len(pos)

83

In [69]:
posts[1]

" 안녕하세요 ICT멘토링 서포터즈 7기 손영주입니다제가 알려드리는 2번째 ICT트렌드는 바로 '딥러닝'입니다'딥러닝'이 무엇이냐고요? '딥러닝'(Deep Learning) 쉽게 말씀드리자면 학습을 통한 생각하는 컴퓨터가까운 예시는 이세돌 9단과 바둑을 두었던 알파고인데요.역사적인 사건 혹은 대결이었던 이 대전은 ICT에 관심이 없었던 많은 사람들에게도 인공지능(AI)에 대한 관심을 불러일으켰습니다.많은 사람들과 이세돌은 경기 전, 낙승을 예상했지만 경기가 지날수록 이길 수 없는 상대와의 대전인 것처럼 되었습니다. 구글의 알파고는 딥러닝 기술에 기반한 프로그램인데요딥러닝에 대해 알아보겠습니다딥러닝이란 많은 데이터를 컴퓨터에 입력하고 비슷한 것끼리 분류하도록하는 기술입니다. 우리는 자각할 수 없지만 인간의 두뇌가 수많은 데이터 속에서 패턴을 발견한 뒤 사물을 구분하는 정보처리 방식을 모방한 것입니다. 데이터를 기반으로 기계가 스스로 인지·추론·판단할 수 있게 됩니다. 위 2개의 사진은 생활 속의 딥러닝입니다.딥러닝이라면 '나'와는 아주 먼 이야기 같겠지만,얼굴 인식 기술을 페이스북 및 음성 인식 기술을 탑재한 아이폰 등일상 속에서 딥러닝을 마주하고 있습니다.현재 딥러닝은 사진 분류뿐만 아니라 문학, 그림, 게임 등다양한 산업에서 결합하고 있습니다. 이러한 딥러닝에도 한계가 있기 마련인데요!우선 '정확성'의 문제입니다.무적으로 보였던 알파고가 4번째 대국에서 패배, 페이스북이나 구글포토도 가끔 엉뚱한 사람을 태그하거나 엉뚱한 사물로 분류하기도 합니다.무조건 데이터가 많다고 해결되는 문제는 아닙니다.기계의 학습이 완벽해지는 시점이 있으며 이를 넘으면 오히려 정확성이 떨어집니다.다음은 '악용의 가능성'인데요. 예를 들면 영화 <아이로봇>처럼 틀린 정보를 기계에 학습시켜 옳지 않은 정보를 기계가 옳다고 생각하게 만든다면 영화처럼 비극이 일어나지 말라는 법은 없습니다.기하급수적인 데이터와 알고리즘의 발전으로 이러한 한계를넘어서다 보면 딥러닝이 적용될 수 있는 분야는 무궁

In [70]:
posts[3]

' 최근 알파고 기사가 계속 나오길래 잠깐 기사를 보다가... 알파고가 일부 소스코드를 공개했다고 합니다. 진짜 공개했는지는 모르겠고 replication 버전만 공개되어있습니다. Rochester-NRT/AlphaGoAlphaGo - A replication of DeepMind\'s 2016 Nature publication, "Mastering the game of Go with deep neural networks and tree searc...github.com메인으로 들어가면 다음과 같은 화면이 나옵니다.지금시간 기준으로 21시간전에 소스코드를 업데이트 하였네요... 파이썬으로 구성되어 있네요. 대세는 오픈소스! 저 링크를 따라가보면 또 다른 오픈소스가 나옵니다. http://pachi.or.cz/ 바둑 알고리즘 오픈 소스입니다. 메인에 있는 소스코드들 중에 중요한 내용이 있나 확인해 봤는데 특별히 없네요. training 폴더안의 소스코드는 빈통이고요. models 폴더의 메인 스켈레톤도 빈통이예요 ㅜㅜ 몇몇개는 오픈소스에서 따온거 같고...하지만 몇몇 의미있는 코드들도 있습니다. deep_polcy.py 부분인데요...소스 코드를 살펴보니 딥러닝을 위해 Keras 라이브러리를 사용하고 모델 두개 중 Sequential 모델을 사용하였네요.딥러닝에 크게 관심이 없었는데 라이브러리를 보니까 멋져요 !이렇게 쉽게 딥러닝을 할 수 있는 라이브러리가 있다니!!! Keras Documentationkeras.io ..... 그외에 공개 내용중엔 특별한게 없는거 같네요.알파고 테스트 소스에 바둑판 배열은 있네요... 남은 3판은 누가 이길까요? 개인적으로는 알파고의 패턴을 잡아내서 이세돌씨가 이겼으면 하는 생각입니다. '