# Deep Neural Network

## 은닉층 추가 버젼 

In [1]:
import tensorflow as tf
import tensorlayer as tl 

## TensorFlow로 논리 문제 풀어보기

### 기본 그래프 만들기
 - GPU 에서 이산형 데이터 연산이 빠르다. Core수가 多.
 - 그래프 형태로 식을 구성한다. ( 중위계산식 형태로 ) 
 - <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/Sorted_binary_tree.svg/500px-Sorted_binary_tree.svg.png" width=500>

In [2]:
tf.reset_default_graph()
tl.layers.set_name_reuse(enable=True)

## 신경망 만들기

In [3]:
x = tf.placeholder(tf.float32, [None, 2]) # 입력 데이터

In [4]:
network = tl.layers.InputLayer(x) # 입력층

  tensorlayer:Instantiate InputLayer  input_layer: (?, 2)


 - Hidden Layer 숫자를 증가.
 - 빡빡한 신호 : DenseLayer
 - 덜빡빡 : SparseLayer
 - n_units : 세포의 수

In [5]:
network = tl.layers.DenseLayer(network, n_units=2, act=tf.sigmoid, name="hidden1") # 은닉층

  tensorlayer:Instantiate DenseLayer  hidden1: 2, sigmoid


In [6]:
network = tl.layers.DenseLayer(network, n_units=3, act=tf.sigmoid, name="hidden2") # 은닉층

  tensorlayer:Instantiate DenseLayer  hidden2: 3, sigmoid


  - denseLayer 추가
  - output 1

In [7]:
network = tl.layers.DenseLayer(network, n_units=1, act=tf.sigmoid, name="output") # 출력층

  tensorlayer:Instantiate DenseLayer  output: 1, sigmoid


## 비용

In [8]:
predict = network.outputs # 예측값

In [9]:
y = tf.placeholder(tf.float32, [None, 1]) # 실제 값

In [10]:
cost = tl.cost.binary_cross_entropy(network.outputs, y)

## 데이터 설정

In [11]:
import numpy

In [12]:
xdata = numpy.array([[0, 0], [1, 0], [0, 1], [1, 1]])
ydata = numpy.array([0, 1, 1, 0]).reshape((4, 1))
data = {x: xdata, y: ydata}

In [14]:
xdata

array([[0, 0],
       [1, 0],
       [0, 1],
       [1, 1]])

## 경사하강법
 - learning_rate가 너무 작으면 학습 속도가 느리고, 너무 높으면 학습이 불안정하게 된다. 적당히 잘 설정할 것

In [56]:
gd = tf.train.RMSPropOptimizer(learning_rate=0.01, momentum=0.9)
train_step = gd.minimize(cost)    # cost를 최소화한다

## 세션과 변수 초기화

In [57]:
session = tf.InteractiveSession()
session.run(tf.global_variables_initializer())

## 그래프를 세션에서 실행

In [58]:
predict.eval(data)  # 초기 예측값

array([[ 0.54193765],
       [ 0.54196239],
       [ 0.54188216],
       [ 0.54190683]], dtype=float32)

In [59]:
cost.eval(data)  # 초기 비용

0.69667453

## 한 단계 학습

In [60]:
train_step.run(data)

In [61]:
predict.eval(data)  # 예측이 변화

array([[ 0.54175007],
       [ 0.54177475],
       [ 0.5416947 ],
       [ 0.54171932]], dtype=float32)

In [62]:
cost.eval(data)  # 비용이 감소한 것을 확인

0.69664294

## 반복해서 학습

In [63]:
tl.utils.fit(session, network, train_step, cost, xdata, ydata, x, y,
             batch_size=4,  # 한 번에 4개의 데이터 학습
             n_epoch=1000,  # 최대 1000회까지
             print_freq=100 # 100번 학습마다 비용을 출력
             )

Start training the network ...
Epoch 1 of 1000 took 0.029023s, loss 0.696643
Epoch 100 of 1000 took 0.001000s, loss 0.693147
Epoch 200 of 1000 took 0.001001s, loss 0.693152
Epoch 300 of 1000 took 0.000000s, loss 0.002957
Epoch 400 of 1000 took 0.001000s, loss 0.000037
Epoch 500 of 1000 took 0.001001s, loss 0.000002
Epoch 600 of 1000 took 0.000000s, loss 0.000001
Epoch 700 of 1000 took 0.003004s, loss 0.000001
Epoch 800 of 1000 took 0.000500s, loss 0.000001
Epoch 900 of 1000 took 0.001000s, loss 0.000000
Epoch 1000 of 1000 took 0.000000s, loss 0.000000
Total training time: 0.748005s


In [64]:
predict.eval(data)  # 최종 예측

array([[ 0.00000056],
       [ 0.99999976],
       [ 0.99999976],
       [ 0.00000055]], dtype=float32)

In [65]:
numpy.set_printoptions(suppress=True)

In [66]:
predict.eval(data)

array([[ 0.00000056],
       [ 0.99999976],
       [ 0.99999976],
       [ 0.00000055]], dtype=float32)