# Nerural Nerwork(DeepLearning with tensorflow)

In [9]:
import tensorflow as tf
import tensorlayer as tl

 - 윈도우에서도...가능하다... 

# Tensorflow로 논리문제 풀기 
## 기본 그래프 만들기 

In [10]:
tf.reset_default_graph()

In [11]:
tl.layers.set_name_reuse(enable=True)

In [12]:
g = tf.Graph()

In [13]:
g.as_default()

# 신경망 만들기 

In [14]:
x = tf.placeholder(tf.float32, [None,2]) # 입력데이터(입력층) float 32bits데이터를 행 : None, 열 : 2개 

 - AND 문제 
  - x1   x2   y 에서 x1,x2 가 [None,2] 여기 2에 들어간다.

In [15]:
network = tl.layers.InputLayer(x) # 입력층

  tensorlayer:Instantiate InputLayer  input_layer: (?, 2)


In [16]:
network = tl.layers.DenseLayer(network,n_units=1,act=tf.sigmoid,name = "output") # 입력층의 모든 데이터가 모든 신호를 받는 layer생성

  tensorlayer:Instantiate DenseLayer  output: 1, sigmoid


# 비용 

In [17]:
predict = network.outputs # 예측값

In [18]:
y = tf.placeholder(tf.float32, [None,1]) #실제 값

In [19]:
cost = tl.cost.binary_cross_entropy(network.outputs,y)

# 데이터 설정

In [20]:
import numpy as np

In [21]:
xdata = np.array([[0,0],[1,0],[0,1],[1,1]])
ydata = np.array([0,0,0,1]).reshape([4,1])

In [22]:
xdata

array([[0, 0],
       [1, 0],
       [0, 1],
       [1, 1]])

In [23]:
ydata

array([[0],
       [0],
       [0],
       [1]])

In [24]:
data = {x:xdata,y:ydata}

In [25]:
data

{<tf.Tensor 'Placeholder:0' shape=(?, 2) dtype=float32>: array([[0, 0],
        [1, 0],
        [0, 1],
        [1, 1]]),
 <tf.Tensor 'Placeholder_1:0' shape=(?, 1) dtype=float32>: array([[0],
        [0],
        [0],
        [1]])}

# 경사 하강법 
 - learning_rate 가 너무 작으면 학습속도가 느리고, 너무 높으면 학습이 불안정하다. 적당히 잘....

In [26]:
gd = tf.train.GradientDescentOptimizer(learning_rate=1)

In [27]:
train_step = gd.minimize(cost) # cost를 최소화한다.

# 세션과 변수 초기화 
 - Graphic card로 데이터를 보낸다. 아.... 보내는 모습을 session이라고 한다. 

In [28]:
sess = tf.InteractiveSession()

In [29]:
sess.run(tf.global_variables_initializer())

# 그래프를 세션에서 실행 

In [30]:
predict.eval(data) #초기 예측값

array([[ 0.5       ],
       [ 0.47361392],
       [ 0.51227999],
       [ 0.48587558]], dtype=float32)

In [31]:
cost.eval(data) # 초기 비용.

0.69367099

# 한 단계 학습

In [32]:
sess.run(train_step,data)

In [33]:
predict.eval(data)

array([[ 0.4395614 ],
       [ 0.41618434],
       [ 0.45181215],
       [ 0.42828143]], dtype=float32)

In [34]:
cost.eval(data)

0.64157939

# 반복해서 학습 

In [35]:
tl.utils.fit(sess,network,train_step,cost,xdata,ydata,x,y, batch_size=4, # 한번에 4개의 데이터 학습.
             n_epoch=1000, #최대 1000회까지
             print_freq = 100 # 100번 학습할때마다 비용을 출력 
            )

Start training the network ...
Epoch 1 of 1000 took 0.008511s, loss 0.641579
Epoch 100 of 1000 took 0.000000s, loss 0.142839
Epoch 200 of 1000 took 0.000000s, loss 0.081340
Epoch 300 of 1000 took 0.000501s, loss 0.056370
Epoch 400 of 1000 took 0.000501s, loss 0.042948
Epoch 500 of 1000 took 0.000501s, loss 0.034611
Epoch 600 of 1000 took 0.000500s, loss 0.028947
Epoch 700 of 1000 took 0.000000s, loss 0.024857
Epoch 800 of 1000 took 0.000501s, loss 0.021767
Epoch 900 of 1000 took 0.000501s, loss 0.019354
Epoch 1000 of 1000 took 0.000000s, loss 0.017418
Total training time: 0.354443s


In [36]:
predict.eval(data)

array([[  1.24155449e-05],
       [  2.02214178e-02],
       [  2.02214178e-02],
       [  9.71677899e-01]], dtype=float32)

In [37]:
np.set_printoptions(suppress=True) #수치를 일반적인 형태로 표시하게 설정 

In [38]:
predict.eval(data)

array([[ 0.00001242],
       [ 0.02022142],
       [ 0.02022142],
       [ 0.9716779 ]], dtype=float32)

# 세션 종료 

In [39]:
sess.close()